#debug=true
spring.application.name=paymentsystem
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.jpa.hibernate.ddl-auto=update
jwt.secret=PWYX+KmjC6D6+QMQ6XRvxFGpMjk68jiS8uf9TaRAo5A= #can be genrated using?
management.endpoints.web.exposure.include=*
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console 
#it sets the URL path where the H2 in-memory database web console will be accessible when your Spring Boot app runs.
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG


#DataSource is a standard J2EE interface that defines the connection pool and the database connection configuration.

